import { Ionicons } from '@expo/vector-icons';
import * as Clipboard from 'expo-clipboard';
import { Stack, useLocalSearchParams, useRouter } from 'expo-router';
import React, { useEffect, useMemo, useRef, useState } from 'react';
import { Platform, Pressable, ScrollView, Share, StyleSheet, Text, TextInput, View } from 'react-native';

import { Button, SectionTitle } from '../../src/components/ui';
import { api } from '../../src/lib/api';
import { inviteLink } from '../../src/lib/invite';
import { useAuth } from '../../src/store/useAuth';
import { useStore } from '../../src/store/useStore';
import { Palette, font, radius, spacing, useColors } from '../../src/theme';

export default function InviteScreen() {
  const c = useColors();
  const styles = useMemo(() => makeStyles(c), [c]);
  const router = useRouter();
  const params = useLocalSearchParams<{ groupId?: string; code?: string; created?: string }>();
  const { groupId } = params;
  const justCreated = params.created === '1';
  const groups = useStore((s) => s.groups);
  const refresh = useAuth((s) => s.refresh);

  const group = groups.find((g) => g.id === groupId);
  // Creating a group already minted a code and passed it here, so there is no
  // need to spend a second one.
  const [code, setCode] = useState(params.code ?? '');
  const [joinCode, setJoinCode] = useState('');
  const [status, setStatus] = useState('');
  const [busy, setBusy] = useState(false);
  const autoGenerated = useRef(Boolean(params.code));

  const link = code ? inviteLink(code) : '';

  const generate = async () => {
    if (!groupId) return;
    setBusy(true);
    setStatus('');
    try {
      const { code: fresh } = await api.createInvite(groupId);
      setCode(fresh);
    } catch (err) {
      setStatus(err instanceof Error ? err.message : 'Could not create an invite');
    } finally {
      setBusy(false);
    }
  };

  // Have a link ready the moment the screen opens: the reason to be here is to
  // send someone an invite, and making that a two-step process helped nobody.
  useEffect(() => {
    if (!groupId || autoGenerated.current) return;
    autoGenerated.current = true;
    void generate();
    // generate closes over groupId only, and the ref makes this run once.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [groupId]);

  const copy = async (value: string, label: string) => {
    await Clipboard.setStringAsync(value);
    setStatus(`${label} copied.`);
  };

  const share = async () => {
    if (!link || !group) return;
    const message = `Join "${group.name}" on Split & Track: ${link}`;
    if (Platform.OS === 'web') {
      // navigator.share exists on mobile browsers and recent desktop Safari;
      // everywhere else falling back to the clipboard beats doing nothing.
      const nav = typeof navigator !== 'undefined' ? (navigator as any) : null;
      if (nav?.share) {
        try {
          await nav.share({ title: `Join ${group.name}`, text: message, url: link });
          return;
        } catch {
          // The user dismissed the sheet — not an error worth reporting.
          return;
        }
      }
      await copy(link, 'Link');
      return;
    }
    await Share.share({ message });
  };

  const join = async () => {
    setBusy(true);
    setStatus('');
    try {
      const { group: joined } = await api.join(joinCode.trim().toUpperCase());
      await refresh();
      setJoinCode('');
      // Leaving the user sitting on this modal made a successful join look
      // like nothing had happened. Land them in the group they just joined,
      // exactly as following a share link does.
      router.replace(`/group/${joined.id}`);
    } catch (err) {
      setStatus(err instanceof Error ? err.message : 'Could not join');
    } finally {
      setBusy(false);
    }
  };

  return (
    <ScrollView style={{ flex: 1, backgroundColor: c.bg }} keyboardShouldPersistTaps="handled">
      <Stack.Screen options={{ title: justCreated ? 'Share your group' : 'Invite & join' }} />

      {group ? (
        <>
          {justCreated ? (
            <View style={styles.banner}>
              <Ionicons name="checkmark-circle" size={20} color={c.owed} />
              <Text style={[font.small, { color: c.text, marginLeft: spacing.sm, flex: 1 }]}>
                "{group.name}" created
              </Text>
            </View>
          ) : null}

          <SectionTitle>Invite someone to {group.name}</SectionTitle>

          {link ? (
            <>
              <Pressable onPress={() => void copy(link, 'Link')} style={styles.linkBox}>
                <Text style={[font.small, { color: c.text }]} numberOfLines={2}>
                  {link}
                </Text>
                <View style={styles.copyRow}>
                  <Ionicons name="copy-outline" size={14} color={c.textMuted} />
                  <Text style={[font.small, { color: c.textMuted, marginLeft: 5 }]}>
                    Tap to copy · expires in 14 days
                  </Text>
                </View>
              </Pressable>

              <View style={{ paddingHorizontal: spacing.lg }}>
                <Button title="Share link" onPress={() => void share()} />
              </View>

              <Text style={styles.orText}>or share the code</Text>
              <Pressable onPress={() => void copy(code, 'Code')} style={styles.codeBox}>
                <Text style={[font.h1, { color: c.owed, letterSpacing: 4 }]}>{code}</Text>
              </Pressable>
            </>
          ) : null}

          <View style={{ paddingHorizontal: spacing.lg, paddingBottom: spacing.lg }}>
            <Button
              title={code ? 'Generate a new link' : 'Create invite link'}
              variant={code ? 'secondary' : 'primary'}
              onPress={() => void generate()}
              loading={busy}
            />
            {justCreated ? (
              <Button
                title="Go to group"
                variant="secondary"
                onPress={() => router.replace(`/group/${group.id}`)}
                style={{ marginTop: spacing.sm }}
              />
            ) : null}
          </View>
        </>
      ) : null}

      <SectionTitle>Join a group</SectionTitle>
      <TextInput
        value={joinCode}
        onChangeText={setJoinCode}
        placeholder="ABCD1234"
        placeholderTextColor={c.textFaint}
        autoCapitalize="characters"
        autoCorrect={false}
        style={styles.input}
      />
      <View style={{ padding: spacing.lg }}>
        <Button
          title="Join group"
          onPress={() => void join()}
          disabled={joinCode.trim().length < 4}
          loading={busy}
        />
      </View>

      {status ? (
        <Text style={[font.small, { color: c.textMuted, paddingHorizontal: spacing.lg }]}>
          {status}
        </Text>
      ) : null}
    </ScrollView>
  );
}

const makeStyles = (c: Palette) =>
  StyleSheet.create({
    banner: {
      flexDirection: 'row',
      alignItems: 'center',
      margin: spacing.lg,
      marginBottom: 0,
      padding: spacing.md,
      borderRadius: radius.md,
      backgroundColor: c.owedTint,
    },
    linkBox: {
      marginHorizontal: spacing.lg,
      marginBottom: spacing.md,
      padding: spacing.md,
      backgroundColor: c.surface,
      borderRadius: radius.md,
    },
    copyRow: { flexDirection: 'row', alignItems: 'center', marginTop: spacing.sm },
    orText: {
      ...font.small,
      color: c.textFaint,
      textAlign: 'center',
      marginTop: spacing.lg,
      marginBottom: spacing.sm,
    },
    codeBox: {
      alignItems: 'center',
      marginHorizontal: spacing.lg,
      marginBottom: spacing.md,
      paddingVertical: spacing.lg,
      backgroundColor: c.owedTint,
      borderRadius: radius.lg,
    },
    input: {
      ...font.h3,
      marginHorizontal: spacing.lg,
      padding: spacing.md,
      backgroundColor: c.surface,
      borderRadius: radius.md,
      color: c.text,
      letterSpacing: 2,
    },
  });
